// Templates de séances courantes pour middle distance running
export interface SessionTemplate {
  id: string
  name: string
  description: string
  sessionType: 'ENDURANCE' | 'FRACTIONNE' | 'SEUIL' | 'VMA' | 'RECUPERATION' | 'COMPETITION' | 'AUTRE'
  zone1Endurance: number
  zone2Seuil: number
  zone3SupraMax: number
  zoneVitesse: number
  totalVolume: number
  targetTimes?: string
  notes?: string
  category: 'endurance' | 'seuil' | 'vma' | 'fractionne' | 'repos' | 'competition'
}

export const SESSION_TEMPLATES: SessionTemplate[] = [
  // Endurance
  {
    id: 'jog-1h',
    name: 'JOG 1H',
    description: 'JOG 1H',
    sessionType: 'ENDURANCE',
    zone1Endurance: 12,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 12,
    category: 'endurance',
  },
  {
    id: 'jog-1h-muscu',
    name: 'JOG 1H & MUSCU',
    description: 'JOG 1H & MUSCU',
    sessionType: 'ENDURANCE',
    zone1Endurance: 10,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 10,
    category: 'endurance',
    notes: 'Séance endurance + renforcement musculaire',
  },
  {
    id: 'jog-40',
    name: 'JOG 40\'',
    description: 'JOG 40\'',
    sessionType: 'ENDURANCE',
    zone1Endurance: 8,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 8,
    category: 'endurance',
  },
  {
    id: 'jog-30',
    name: 'JOG 30\'',
    description: 'JOG 30\'',
    sessionType: 'ENDURANCE',
    zone1Endurance: 6,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 6,
    category: 'endurance',
  },
  {
    id: 'sl-1h30',
    name: 'SL 1H30',
    description: 'Sortie Longue 1H30',
    sessionType: 'ENDURANCE',
    zone1Endurance: 18,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 18,
    category: 'endurance',
    notes: 'Sortie longue endurance fondamentale',
  },
  {
    id: 'sl-15k',
    name: 'SL 15K',
    description: 'Sortie Longue 15K',
    sessionType: 'ENDURANCE',
    zone1Endurance: 15,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 15,
    category: 'endurance',
  },
  {
    id: 'sl-20k',
    name: 'SL 20K',
    description: 'Sortie Longue 20K',
    sessionType: 'ENDURANCE',
    zone1Endurance: 20,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 20,
    category: 'endurance',
  },
  {
    id: 'actif-1h',
    name: 'ACTIF 1H',
    description: 'ACTIF 1H (~4\'00/km)',
    sessionType: 'ENDURANCE',
    zone1Endurance: 15,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 15,
    category: 'endurance',
    notes: 'Allure active ~4\'00/km',
  },

  // Seuils
  {
    id: 'tempo-10k',
    name: 'TEMPO 10K',
    description: 'TEMPO 10K (~3\'45/km)',
    sessionType: 'SEUIL',
    zone1Endurance: 2,
    zone2Seuil: 10,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 12,
    category: 'seuil',
    notes: 'Tempo en négatif split',
  },
  {
    id: 'sv1-2x15',
    name: 'SV1 2 x 15\' r5',
    description: '2 x 15\' (Sv1) r5',
    sessionType: 'SEUIL',
    zone1Endurance: 2,
    zone2Seuil: 6,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 8,
    category: 'seuil',
    targetTimes: '~3\'45/km',
  },
  {
    id: 'sv1-3x10',
    name: 'SV1 3 x 10\' r3',
    description: '3 x 10\' (Sv1) r3',
    sessionType: 'SEUIL',
    zone1Endurance: 1,
    zone2Seuil: 5,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 6,
    category: 'seuil',
  },
  {
    id: 'sv2-5x4',
    name: 'SV2 5 x 4\' r1\'30',
    description: 'SV2 5 x 4\' r1\'30',
    sessionType: 'SEUIL',
    zone1Endurance: 1,
    zone2Seuil: 5,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 6,
    category: 'seuil',
    targetTimes: '~3\'15/km',
  },
  {
    id: 'sv2-2x6',
    name: 'SV2 2 x 6\' r2',
    description: 'SV2 2 x 6\' (~3\'15/km) r2',
    sessionType: 'SEUIL',
    zone1Endurance: 1,
    zone2Seuil: 4,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 5,
    category: 'seuil',
  },
  {
    id: 'sv2-8x2',
    name: 'SV2 8 x 2\' r1',
    description: 'SV2 8 x 2\' (~3\'05/km) r1',
    sessionType: 'SEUIL',
    zone1Endurance: 1,
    zone2Seuil: 4,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 5,
    category: 'seuil',
  },

  // VMA
  {
    id: 'vma-8x1',
    name: 'VMA 8 x 1\' r1',
    description: 'VMA (100%) 8 x 1\' r1',
    sessionType: 'VMA',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 2.6,
    zoneVitesse: 0,
    totalVolume: 4.6,
    category: 'vma',
    notes: 'VMA à 100%',
  },
  {
    id: 'vma-6x30-30',
    name: 'VMA 2 x (6 x 30/30)',
    description: 'VMA 2 x (6 x 30/30 r2) R2',
    sessionType: 'VMA',
    zone1Endurance: 1,
    zone2Seuil: 0,
    zone3SupraMax: 2.4,
    zoneVitesse: 0,
    totalVolume: 3.4,
    category: 'vma',
  },
  {
    id: 'vma-10x600',
    name: 'VMA 10 x 600m',
    description: 'VMA 10 x 600m r1\'15 (~1\'40)',
    sessionType: 'VMA',
    zone1Endurance: 1,
    zone2Seuil: 0,
    zone3SupraMax: 1.8,
    zoneVitesse: 0,
    totalVolume: 2.8,
    category: 'vma',
  },
  {
    id: 'vma-8x400',
    name: 'VMA 8 x 400m',
    description: 'VMA 8 x 400m r1\' (~1\'06)',
    sessionType: 'VMA',
    zone1Endurance: 1,
    zone2Seuil: 0,
    zone3SupraMax: 1.2,
    zoneVitesse: 0,
    totalVolume: 2.2,
    category: 'vma',
  },

  // Fractionné
  {
    id: 'frac-6x800-4x200',
    name: '6 x 800 & 4 x 200',
    description: '6 x 800 & 4 x 200 r200',
    sessionType: 'FRACTIONNE',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 1.5,
    totalVolume: 3.5,
    category: 'fractionne',
    notes: 'Fractionné vitesse',
  },
  {
    id: 'frac-15x400',
    name: '15 x 400m',
    description: '15 x 400m r100 actif (~3\'10)',
    sessionType: 'FRACTIONNE',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 1.5,
    totalVolume: 3.5,
    category: 'fractionne',
  },
  {
    id: 'frac-8x400',
    name: '8 x 400m',
    description: '8 x 400m (~1\'06/04) r2',
    sessionType: 'FRACTIONNE',
    zone1Endurance: 1,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 1.2,
    totalVolume: 2.2,
    category: 'fractionne',
  },
  {
    id: 'frac-6x200',
    name: '6 x 200m',
    description: '6 x 200m r200 marche (~28/29\'\')',
    sessionType: 'FRACTIONNE',
    zone1Endurance: 0.5,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 1.2,
    totalVolume: 1.7,
    category: 'fractionne',
  },
  {
    id: 'frac-10x400',
    name: '10 x 400m',
    description: '10 x 400m r30 (~1\'12)',
    sessionType: 'FRACTIONNE',
    zone1Endurance: 1,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 1,
    totalVolume: 2,
    category: 'fractionne',
  },
  {
    id: 'frac-1-6k-1-2k',
    name: '1,6K + 1,2K + 0,8K + 2 x 0,4K',
    description: '1,6K 1,2K 0,8 & 2 x 0,4 (100%)',
    sessionType: 'FRACTIONNE',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 2.8,
    zoneVitesse: 0,
    totalVolume: 4.8,
    category: 'fractionne',
  },

  // Côtes
  {
    id: 'cotes-10x200',
    name: 'CÔTES 10 x 200',
    description: 'CÔTES 10 x 200 placement',
    sessionType: 'VMA',
    zone1Endurance: 1,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0.6,
    totalVolume: 1.6,
    category: 'vma',
    notes: 'Côtes pour placement',
  },
  {
    id: 'cotes-2x3-4x2',
    name: 'CÔTES 2 x 3 & 4 x 2',
    description: 'CÔTES LONGUE 2 x 3 & 4 x 2 (bpm Sv2)',
    sessionType: 'SEUIL',
    zone1Endurance: 1,
    zone2Seuil: 2,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 3,
    category: 'seuil',
  },

  // Repos
  {
    id: 'repos',
    name: 'REPOS',
    description: 'REPOS',
    sessionType: 'RECUPERATION',
    zone1Endurance: 0,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 0,
    category: 'repos',
  },

  // Endurance supplémentaires
  {
    id: 'jog-1h30',
    name: 'JOG 1H30',
    description: 'JOG 1H30',
    sessionType: 'ENDURANCE',
    zone1Endurance: 18,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 18,
    category: 'endurance',
  },
  {
    id: 'jog-2h',
    name: 'JOG 2H',
    description: 'JOG 2H',
    sessionType: 'ENDURANCE',
    zone1Endurance: 24,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 24,
    category: 'endurance',
  },
  {
    id: 'actif-1h30',
    name: 'ACTIF 1H30',
    description: 'ACTIF 1H30 (~4\'00/km)',
    sessionType: 'ENDURANCE',
    zone1Endurance: 22,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 22,
    category: 'endurance',
  },
  {
    id: 'sl-25k',
    name: 'SL 25K',
    description: 'Sortie Longue 25K',
    sessionType: 'ENDURANCE',
    zone1Endurance: 25,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 25,
    category: 'endurance',
  },
  {
    id: 'sl-30k',
    name: 'SL 30K',
    description: 'Sortie Longue 30K',
    sessionType: 'ENDURANCE',
    zone1Endurance: 30,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 30,
    category: 'endurance',
  },

  // Seuils supplémentaires
  {
    id: 'sv1-3x12',
    name: 'SV1 3 x 12\' r3',
    description: 'SV1 3 x 12\' r3',
    sessionType: 'SEUIL',
    zone1Endurance: 1.5,
    zone2Seuil: 6.5,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 8,
    category: 'seuil',
  },
  {
    id: 'sv2-3x8',
    name: 'SV2 3 x 8\' r2',
    description: 'SV2 3 x 8\' (~3\'10/km) r2',
    sessionType: 'SEUIL',
    zone1Endurance: 1.5,
    zone2Seuil: 6.5,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 8,
    category: 'seuil',
  },
  {
    id: 'tempo-15k',
    name: 'TEMPO 15K',
    description: 'TEMPO 15K (~3\'50/km)',
    sessionType: 'SEUIL',
    zone1Endurance: 2,
    zone2Seuil: 15,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 17,
    category: 'seuil',
  },
  {
    id: 'tempo-21k',
    name: 'TEMPO 21K',
    description: 'TEMPO 21K (~3\'55/km)',
    sessionType: 'SEUIL',
    zone1Endurance: 2,
    zone2Seuil: 21,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 23,
    category: 'seuil',
  },

  // VMA supplémentaires
  {
    id: 'vma-12x400',
    name: 'VMA 12 x 400m',
    description: 'VMA 12 x 400m r1\' (~1\'08)',
    sessionType: 'VMA',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 1.44,
    zoneVitesse: 0,
    totalVolume: 3.44,
    category: 'vma',
  },
  {
    id: 'vma-5x1000',
    name: 'VMA 5 x 1000m',
    description: 'VMA 5 x 1000m r2\' (~3\'30)',
    sessionType: 'VMA',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 1.5,
    zoneVitesse: 0,
    totalVolume: 3.5,
    category: 'vma',
  },
  {
    id: 'vma-3x2000',
    name: 'VMA 3 x 2000m',
    description: 'VMA 3 x 2000m r3\' (~7\'00)',
    sessionType: 'VMA',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 1.8,
    zoneVitesse: 0,
    totalVolume: 3.8,
    category: 'vma',
  },

  // Fractionné supplémentaires
  {
    id: 'frac-10x400',
    name: '10 x 400m',
    description: '10 x 400m r30 (~1\'12)',
    sessionType: 'FRACTIONNE',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 1,
    totalVolume: 3,
    category: 'fractionne',
  },
  {
    id: 'frac-12x300',
    name: '12 x 300m',
    description: '12 x 300m r200 (~48\'\')',
    sessionType: 'FRACTIONNE',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 1.08,
    totalVolume: 3.08,
    category: 'fractionne',
  },
  {
    id: 'frac-8x600',
    name: '8 x 600m',
    description: '8 x 600m r2\' (~1\'40)',
    sessionType: 'FRACTIONNE',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 1.2,
    totalVolume: 3.2,
    category: 'fractionne',
  },
  {
    id: 'frac-5x1000',
    name: '5 x 1000m',
    description: '5 x 1000m r2\' (~2\'50)',
    sessionType: 'FRACTIONNE',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 1.25,
    totalVolume: 3.25,
    category: 'fractionne',
  },

  // Côtes supplémentaires
  {
    id: 'cotes-15x200',
    name: 'CÔTES 15 x 200',
    description: 'CÔTES 15 x 200 placement',
    sessionType: 'VMA',
    zone1Endurance: 1.5,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0.9,
    totalVolume: 2.4,
    category: 'vma',
  },
  {
    id: 'cotes-20x100',
    name: 'CÔTES 20 x 100',
    description: 'CÔTES COURTES 20 x 100',
    sessionType: 'VMA',
    zone1Endurance: 1,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0.6,
    totalVolume: 1.6,
    category: 'vma',
  },
  {
    id: 'cotes-3x5',
    name: 'CÔTES 3 x 5',
    description: 'CÔTES LONGUES 3 x 5\' (bpm Sv2)',
    sessionType: 'SEUIL',
    zone1Endurance: 1.5,
    zone2Seuil: 3,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 4.5,
    category: 'seuil',
  },

  // Musculation
  {
    id: 'muscu-complete',
    name: 'MUSCU Complète',
    description: 'MUSCU Complète',
    sessionType: 'AUTRE',
    zone1Endurance: 0,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 0,
    category: 'competition',
    notes: 'Renforcement musculaire complet',
  },
  {
    id: 'muscu-haut',
    name: 'MUSCU Haut du corps',
    description: 'MUSCU Haut du corps',
    sessionType: 'AUTRE',
    zone1Endurance: 0,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 0,
    category: 'competition',
    notes: 'Renforcement haut du corps',
  },
  {
    id: 'ppg',
    name: 'PPG',
    description: 'PPG (Préparation Physique Générale)',
    sessionType: 'AUTRE',
    zone1Endurance: 0,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 0,
    category: 'competition',
    notes: 'Préparation physique générale',
  },
  {
    id: 'gainage',
    name: 'Gainage',
    description: 'Gainage',
    sessionType: 'AUTRE',
    zone1Endurance: 0,
    zone2Seuil: 0,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 0,
    category: 'competition',
    notes: 'Séance de gainage',
  },

  // Compétitions
  {
    id: 'comp-800m',
    name: 'Compétition 800m',
    description: 'COMPETITION 800m',
    sessionType: 'COMPETITION',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 0.8,
    zoneVitesse: 0,
    totalVolume: 2.8,
    category: 'competition',
  },
  {
    id: 'comp-1500m',
    name: 'Compétition 1500m',
    description: 'COMPETITION 1500m',
    sessionType: 'COMPETITION',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 1.5,
    zoneVitesse: 0,
    totalVolume: 3.5,
    category: 'competition',
  },
  {
    id: 'comp-3000m',
    name: 'Compétition 3000m',
    description: 'COMPETITION 3000m',
    sessionType: 'COMPETITION',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 3,
    zoneVitesse: 0,
    totalVolume: 5,
    category: 'competition',
  },
  {
    id: 'comp-5000m',
    name: 'Compétition 5000m',
    description: 'COMPETITION 5000m',
    sessionType: 'COMPETITION',
    zone1Endurance: 2,
    zone2Seuil: 0,
    zone3SupraMax: 5,
    zoneVitesse: 0,
    totalVolume: 7,
    category: 'competition',
  },
  {
    id: 'comp-10k',
    name: 'Compétition 10K',
    description: 'COMPETITION 10K',
    sessionType: 'COMPETITION',
    zone1Endurance: 2,
    zone2Seuil: 8,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 10,
    category: 'competition',
  },
  {
    id: 'comp-semi',
    name: 'Compétition Semi',
    description: 'COMPETITION Semi-Marathon',
    sessionType: 'COMPETITION',
    zone1Endurance: 2,
    zone2Seuil: 19,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 21,
    category: 'competition',
  },
  {
    id: 'comp-marathon',
    name: 'Compétition Marathon',
    description: 'COMPETITION Marathon',
    sessionType: 'COMPETITION',
    zone1Endurance: 2,
    zone2Seuil: 40,
    zone3SupraMax: 0,
    zoneVitesse: 0,
    totalVolume: 42,
    category: 'competition',
  },
]

export const TEMPLATES_BY_CATEGORY = {
  endurance: SESSION_TEMPLATES.filter(t => t.category === 'endurance'),
  seuil: SESSION_TEMPLATES.filter(t => t.category === 'seuil'),
  vma: SESSION_TEMPLATES.filter(t => t.category === 'vma'),
  fractionne: SESSION_TEMPLATES.filter(t => t.category === 'fractionne'),
  repos: SESSION_TEMPLATES.filter(t => t.category === 'repos'),
  competition: SESSION_TEMPLATES.filter(t => t.category === 'competition'),
}

